[package]
name = "procgeo-sops"
version.workspace = true
edition.workspace = true

[dependencies]
procgeo-core = { path = "../procgeo-core" }
glam = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
nalgebra = { workspace = true }
robust = { workspace = true }
quadrs = "1.0"

[dev-dependencies]
approx = { workspace = true }

[features]
default = ["creation", "transform", "normals", "merge", "attributes", "groups_sops", "delete", "copy", "reshape", "scatter", "topology", "measure_sops", "utility_sops", "color", "voronoi", "deform", "boolean", "quadwild"]
creation = []
transform = []
normals = []
merge = []
attributes = []
groups_sops = []
delete = []
copy = []
reshape = []
scatter = []
topology = []
measure_sops = []
utility_sops = []
color = []
voronoi = ["reshape"]
deform = []
boolean = []
quadwild = []
