/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_geometry_free: (a: number, b: number) => void;
export const clip: (a: number, b: number) => [number, number, number];
export const color: (a: number, b: number) => [number, number, number];
export const computeNormals: (a: number) => [number, number, number];
export const copyToPoints: (a: number, b: number) => [number, number, number];
export const createBox: (a: number) => [number, number, number];
export const createCircle: (a: number) => [number, number, number];
export const createGrid: (a: number) => [number, number, number];
export const createLine: (a: number) => [number, number, number];
export const createSphere: (a: number) => [number, number, number];
export const createTorus: (a: number) => [number, number, number];
export const createTube: (a: number) => [number, number, number];
export const fuse: (a: number, b: number) => [number, number, number];
export const geometry_boundingBox: (a: number) => any;
export const geometry_getColors: (a: number) => [number, number];
export const geometry_getNormals: (a: number) => [number, number];
export const geometry_getPositions: (a: number) => [number, number];
export const geometry_getTriangleIndices: (a: number) => [number, number];
export const geometry_new: () => number;
export const geometry_numPoints: (a: number) => number;
export const geometry_numPrims: (a: number) => number;
export const geometry_numVertices: (a: number) => number;
export const geometry_pointPos: (a: number, b: number) => [number, number];
export const geometry_toGlb: (a: number) => [number, number, number, number];
export const geometry_toObj: (a: number) => [number, number, number, number];
export const polyExtrude: (a: number, b: number) => [number, number, number];
export const reverse: (a: number) => [number, number, number];
export const scatter: (a: number, b: number) => [number, number, number];
export const smooth: (a: number, b: number) => [number, number, number];
export const subdivide: (a: number, b: number) => [number, number, number];
export const transform: (a: number, b: number) => [number, number, number];
export const voronoiFracture: (a: number, b: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
