/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function createBox(params?: any | undefined | null): Geometry
export declare function createGrid(params?: any | undefined | null): Geometry
export declare function createSphere(params?: any | undefined | null): Geometry
export declare function createLine(params?: any | undefined | null): Geometry
export declare function createCircle(params?: any | undefined | null): Geometry
export declare function createTube(params?: any | undefined | null): Geometry
export declare function createTorus(params?: any | undefined | null): Geometry
export declare function revolve(geo: Geometry, params?: any | undefined | null): Geometry
export declare function createMetaball(params?: any | undefined | null): Geometry
export declare function transform(geo: Geometry, params?: any | undefined | null): Geometry
export declare function computeNormals(geo: Geometry): Geometry
/**
 * Merge multiple Geometry objects. Accepts an array of Geometry instances.
 * Because napi-rs does not support Vec<&T> for napi classes, this function
 * takes a raw JS value and extracts the stored geometry via a workaround:
 * callers should pass an array of Geometry objects created by this module.
 *
 * Implementation: each Geometry is cloned internally when passed through napi.
 * We accept Vec<ClassInstance<Geometry>> which napi-rs does support.
 */
export declare function merge(geometries: Array<Geometry>): Geometry
export declare function subdivide(geo: Geometry, params?: any | undefined | null): Geometry
export declare function scatter(geo: Geometry, params?: any | undefined | null): Geometry
export declare function copyToPoints(source: Geometry, target: Geometry): Geometry
export declare function polyExtrude(geo: Geometry, params?: any | undefined | null): Geometry
export declare function smooth(geo: Geometry, params?: any | undefined | null): Geometry
export declare function clip(geo: Geometry, params?: any | undefined | null): Geometry
export declare function polyBevel(geo: Geometry, params?: any | undefined | null): Geometry
export declare function polyWire(geo: Geometry, params?: any | undefined | null): Geometry
export declare function polyReduce(geo: Geometry, params?: any | undefined | null): Geometry
export declare function polyFill(geo: Geometry, params?: any | undefined | null): Geometry
export declare function reverse(geo: Geometry): Geometry
export declare function resample(geo: Geometry, params?: any | undefined | null): Geometry
export declare function sort(geo: Geometry, params?: any | undefined | null): Geometry
export declare function fuse(geo: Geometry, params?: any | undefined | null): Geometry
export declare function connectivity(geo: Geometry, params?: any | undefined | null): Geometry
export declare function color(geo: Geometry, params?: any | undefined | null): Geometry
export declare function enumerateAttrib(geo: Geometry, params?: any | undefined | null): Geometry
export declare function measure(geo: Geometry, params?: any | undefined | null): Geometry
export declare function blast(geo: Geometry, params?: any | undefined | null): Geometry
export declare function deleteGeo(geo: Geometry, params?: any | undefined | null): Geometry
export declare function voronoiFracture(geo: Geometry, points: Geometry, params?: any | undefined | null): Geometry
export declare function attribTransfer(dest: Geometry, source: Geometry, params?: any | undefined | null): Geometry
export declare function attribCopy(dest: Geometry, source?: Geometry | undefined | null, params?: any | undefined | null): Geometry
export declare function attribRandomize(geo: Geometry, params?: any | undefined | null): Geometry
export declare function attribSort(geo: Geometry, params?: any | undefined | null): Geometry
export declare function attribBlur(geo: Geometry, params?: any | undefined | null): Geometry
export declare function attribFill(geo: Geometry, params?: any | undefined | null): Geometry
export declare function attribNoise(geo: Geometry, params?: any | undefined | null): Geometry
export declare function attribCreate(geo: Geometry, params?: any | undefined | null): Geometry
export declare function attribDelete(geo: Geometry, params?: any | undefined | null): Geometry
export declare function attribRename(geo: Geometry, params?: any | undefined | null): Geometry
export declare function attribPromote(geo: Geometry, params?: any | undefined | null): Geometry
export declare function groupCreate(geo: Geometry, params?: any | undefined | null): Geometry
export declare function groupCombine(geo: Geometry, params?: any | undefined | null): Geometry
export declare function writeObj(geo: Geometry, path: string): void
export declare function writeGlb(geo: Geometry, path: string): void
/**
 * Execute any registered SOP by name with JSON params.
 * Uses Rust/snake_case field names for params (matching serde serialization).
 */
export declare function executeSop(name: string, geo: Geometry, params?: any | undefined | null): Geometry
/** Execute a creation SOP (no input geometry required). */
export declare function executeSopCreate(name: string, params?: any | undefined | null): Geometry
/** List all registered SOP names. */
export declare function listSops(): Array<string>
export declare function executeCopCreate(name: string, params?: any | undefined | null): CopImage
export declare function executeCop(name: string, image: CopImage, params?: any | undefined | null): CopImage
export declare function executeCopComposite(name: string, imageA: CopImage, imageB: CopImage, params?: any | undefined | null): CopImage
export declare function listCops(): Array<string>
export declare function saveCopImage(image: CopImage, path: string): void
/** Create a solid color image. Params: color ([r,g,b,a] 0-1), width, height */
export declare function copConstant(params?: any | undefined | null): CopImage
/** Create a checkerboard pattern. Params: color_a, color_b ([r,g,b,a]), frequency ([x,y]), width, height */
export declare function copCheckerboard(params?: any | undefined | null): CopImage
/** Create procedural noise image. Params: noise_type (perlin|simplex|worley), frequency, octaves, lacunarity, gain, amplitude, offset ([x,y]), seed, width, height */
export declare function copNoise(params?: any | undefined | null): CopImage
/** Create gradient ramp. Params: ramp_type (linear|radial|box|diagonal), stops ([{position, color}]), width, height */
export declare function copRamp(params?: any | undefined | null): CopImage
/** Load image from disk. Params: path (string) */
export declare function copLoadImage(params?: any | undefined | null): CopImage
/** Gaussian/box blur. Params: blur_type (gaussian|box), radius_x, radius_y */
export declare function copBlur(image: CopImage, params?: any | undefined | null): CopImage
/** Flip image. Params: horizontal (bool), vertical (bool) */
export declare function copFlip(image: CopImage, params?: any | undefined | null): CopImage
/** Mirror across axis. Params: axis (x|y), offset (0-1) */
export declare function copMirror(image: CopImage, params?: any | undefined | null): CopImage
/** Swap RGBA channels. Params: r, g, b, a (each: r|g|b|a|one|zero) */
export declare function copChannelSwap(image: CopImage, params?: any | undefined | null): CopImage
/** Resize image. Params: width, height, filter (nearest|bilinear) */
export declare function copResize(image: CopImage, params?: any | undefined | null): CopImage
/** Rotate image. Params: angle (degrees), center ([x,y] 0-1), filter (nearest|bilinear) */
export declare function copRotate(image: CopImage, params?: any | undefined | null): CopImage
/** Swirl distortion. Params: center ([x,y] 0-1), angle (degrees), radius (0-1) */
export declare function copSwirl(image: CopImage, params?: any | undefined | null): CopImage
/** Composite two images. Params: operation (over|add|multiply|screen|subtract|difference|min|max), mix (0-1) */
export declare function copComposite(imageA: CopImage, imageB: CopImage, params?: any | undefined | null): CopImage
/** Run custom WGSL/GLSL shader. Params: source (string), language (wgsl|glsl), width, height */
export declare function copCustomShader(params?: any | undefined | null, inputA?: CopImage | undefined | null, inputB?: CopImage | undefined | null): CopImage
/** Wrapped Geometry object exposed to JavaScript. */
export declare class Geometry {
  constructor()
  addPoint(x: number, y: number, z: number): number
  setPointPos(index: number, x: number, y: number, z: number): void
  addFace(pointIndices: Array<number>): number
  addPolyline(pointIndices: Array<number>): number
  get numPoints(): number
  get numPrims(): number
  get numVertices(): number
  pointPos(index: number): Array<number>
  boundingBox(): any
  attribNames(class: string): Array<string>
  attribType(class: string, name: string): string | null
  attribSize(class: string, name: string): number | null
  attribData(class: string, name: string): Array<number> | null
  attribDataString(class: string, name: string): Array<string> | null
  primPointIndices(primIndex: number): Array<number>
  primVertexCount(primIndex: number): number
  vertexPoint(vertexIndex: number): number
}
export declare class CopImage {
  get width(): number
  get height(): number
  toBuffer(): Array<number>
}
