/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'procgeo.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./procgeo.android-arm64.node')
          } else {
            nativeBinding = require('@procgeo/core-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'procgeo.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./procgeo.android-arm-eabi.node')
          } else {
            nativeBinding = require('@procgeo/core-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'procgeo.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./procgeo.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@procgeo/core-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'procgeo.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./procgeo.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@procgeo/core-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'procgeo.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./procgeo.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@procgeo/core-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'procgeo.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./procgeo.darwin-universal.node')
      } else {
        nativeBinding = require('@procgeo/core-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'procgeo.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./procgeo.darwin-x64.node')
          } else {
            nativeBinding = require('@procgeo/core-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'procgeo.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./procgeo.darwin-arm64.node')
          } else {
            nativeBinding = require('@procgeo/core-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'procgeo.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./procgeo.freebsd-x64.node')
      } else {
        nativeBinding = require('@procgeo/core-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'procgeo.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./procgeo.linux-x64-musl.node')
            } else {
              nativeBinding = require('@procgeo/core-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'procgeo.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./procgeo.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@procgeo/core-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'procgeo.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./procgeo.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@procgeo/core-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'procgeo.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./procgeo.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@procgeo/core-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'procgeo.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./procgeo.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@procgeo/core-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'procgeo.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./procgeo.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@procgeo/core-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'procgeo.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./procgeo.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@procgeo/core-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'procgeo.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./procgeo.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@procgeo/core-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'procgeo.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./procgeo.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@procgeo/core-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { Geometry, createBox, createGrid, createSphere, createLine, createCircle, createTube, createTorus, revolve, createMetaball, transform, computeNormals, merge, subdivide, scatter, copyToPoints, polyExtrude, smooth, clip, polyBevel, polyWire, polyReduce, polyFill, reverse, resample, sort, fuse, connectivity, color, enumerateAttrib, measure, blast, deleteGeo, voronoiFracture, attribTransfer, attribCopy, attribRandomize, attribSort, attribBlur, attribFill, attribNoise, attribCreate, attribDelete, attribRename, attribPromote, groupCreate, groupCombine, writeObj, writeGlb, executeSop, executeSopCreate, listSops, CopImage, executeCopCreate, executeCop, executeCopComposite, listCops, saveCopImage } = nativeBinding

module.exports.Geometry = Geometry
module.exports.createBox = createBox
module.exports.createGrid = createGrid
module.exports.createSphere = createSphere
module.exports.createLine = createLine
module.exports.createCircle = createCircle
module.exports.createTube = createTube
module.exports.createTorus = createTorus
module.exports.revolve = revolve
module.exports.createMetaball = createMetaball
module.exports.transform = transform
module.exports.computeNormals = computeNormals
module.exports.merge = merge
module.exports.subdivide = subdivide
module.exports.scatter = scatter
module.exports.copyToPoints = copyToPoints
module.exports.polyExtrude = polyExtrude
module.exports.smooth = smooth
module.exports.clip = clip
module.exports.polyBevel = polyBevel
module.exports.polyWire = polyWire
module.exports.polyReduce = polyReduce
module.exports.polyFill = polyFill
module.exports.reverse = reverse
module.exports.resample = resample
module.exports.sort = sort
module.exports.fuse = fuse
module.exports.connectivity = connectivity
module.exports.color = color
module.exports.enumerateAttrib = enumerateAttrib
module.exports.measure = measure
module.exports.blast = blast
module.exports.deleteGeo = deleteGeo
module.exports.voronoiFracture = voronoiFracture
module.exports.attribTransfer = attribTransfer
module.exports.attribCopy = attribCopy
module.exports.attribRandomize = attribRandomize
module.exports.attribSort = attribSort
module.exports.attribBlur = attribBlur
module.exports.attribFill = attribFill
module.exports.attribNoise = attribNoise
module.exports.attribCreate = attribCreate
module.exports.attribDelete = attribDelete
module.exports.attribRename = attribRename
module.exports.attribPromote = attribPromote
module.exports.groupCreate = groupCreate
module.exports.groupCombine = groupCombine
module.exports.writeObj = writeObj
module.exports.writeGlb = writeGlb
module.exports.executeSop = executeSop
module.exports.executeSopCreate = executeSopCreate
module.exports.listSops = listSops
module.exports.CopImage = CopImage
module.exports.executeCopCreate = executeCopCreate
module.exports.executeCop = executeCop
module.exports.executeCopComposite = executeCopComposite
module.exports.listCops = listCops
module.exports.saveCopImage = saveCopImage
