[package]
name = "procgeo-core"
version.workspace = true
edition.workspace = true

[dependencies]
glam = { workspace = true }
smallvec = { workspace = true }
bitvec = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "core_benchmarks"
harness = false
